export const STORAGE_KEYS = {
  FRESH_INSTALL: 'FRESH_INSTALL',
  PET_TYPE: 'PET_TYPE',
  PET_NAME: 'PET_NAME',
  AVATAR: 'AVATAR',
  NOTIFICATIONS_ENABLED: 'NOTIFICATIONS_ENABLED',
  NOTIFICATIONS_TIME: 'NOTIFICATIONS_TIME',
  COFFEE_PURCHASED: 'COFFEE_PURCHASED',
  USE_RATING_BUTTONS: 'USE_RATING_BUTTONS',
  THEME_MODE: 'THEME_MODE',
};
