export const STORAGE_KEYS = {
  FRESH_INSTALL: 'FRESH_INSTALL',
  USER_LANGUAGE: 'USER_LANGUAGE',
  PET_TYPE: 'PET_TYPE',
  PET_NAME: 'PET_NAME',
  AVATAR: 'AVATAR',
  NOTIFICATIONS_ENABLED: 'NOTIFICATIONS_ENABLED',
  LAST_REMINDER_DATE: 'LAST_REMINDER_DATE',
  COFFEE_PURCHASED: 'COFFEE_PURCHASED',
};
