export const STORAGE_KEYS = {
  PET_TYPE: 'PET_TYPE',
  PET_NAME: 'PET_NAME',
  AVATAR: 'AVATAR',
  NOTIFICATIONS_ENABLED: 'NOTIFICATIONS_ENABLED',
  NOTIFICATIONS_TIME: 'NOTIFICATIONS_TIME',
  COFFEE_PURCHASED: 'COFFEE_PURCHASED',
  USE_RATING_BUTTONS: 'USE_RATING_BUTTONS',
  THEME_MODE: 'THEME_MODE',
  FIRST_INSTALL_DATE: 'FIRST_INSTALL_DATE',
  SUPPORT_DIALOG_SHOWN: 'SUPPORT_DIALOG_SHOWN',
};
